CREATE TABLE `atendimentos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`atendimento` varchar(64) NOT NULL,
	`paciente_id` int NOT NULL,
	`data_atendimento` timestamp NOT NULL,
	`semana` int,
	`tipo_atendimento` varchar(100),
	`procedimento` varchar(255),
	`codigos_cbhpm` text,
	`nome_paciente` varchar(255),
	`local` varchar(100),
	`convenio` varchar(100),
	`plano_convenio` varchar(100),
	`pagamento_efetivado` boolean DEFAULT false,
	`pagamento_postergado` varchar(50),
	`data_envio_faturamento` date,
	`data_esperada_pagamento` date,
	`faturamento_previsto` decimal(10,2),
	`registro_manual_valor_hm` decimal(10,2),
	`faturamento_previsto_final` decimal(10,2),
	`data_pagamento` date,
	`nota_fiscal_correspondente` varchar(100),
	`observacoes` text,
	`faturamento_leticia` decimal(10,2),
	`faturamento_ag_lu` decimal(10,2),
	`mes` int,
	`ano` int,
	`trimestre` varchar(10),
	`trimestre_ano` varchar(20),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `atendimentos_id` PRIMARY KEY(`id`),
	CONSTRAINT `atendimentos_atendimento_unique` UNIQUE(`atendimento`)
);
--> statement-breakpoint
CREATE TABLE `pacientes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`id_paciente` varchar(64) NOT NULL,
	`data_inclusao` date,
	`pasta_paciente` varchar(255),
	`nome` varchar(255) NOT NULL,
	`data_nascimento` date,
	`sexo` enum('M','F','Outro'),
	`cpf` varchar(14),
	`nome_mae` varchar(255),
	`email` varchar(320),
	`telefone` varchar(20),
	`endereco` varchar(500),
	`bairro` varchar(100),
	`cep` varchar(10),
	`cidade` varchar(100),
	`uf` varchar(2),
	`pais` varchar(100) DEFAULT 'Brasil',
	`operadora_1` varchar(100),
	`plano_modalidade_1` varchar(100),
	`matricula_convenio_1` varchar(100),
	`vigente_1` varchar(50),
	`privativo_1` varchar(50),
	`operadora_2` varchar(100),
	`plano_modalidade_2` varchar(100),
	`matricula_convenio_2` varchar(100),
	`vigente_2` varchar(50),
	`privativo_2` varchar(50),
	`obito_perda` varchar(100),
	`data_obito_last_fu` date,
	`status_caso` varchar(50) DEFAULT 'Ativo',
	`grupo_diagnostico` varchar(100),
	`diagnostico_especifico` text,
	`tempo_seguimento_anos` decimal(10,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pacientes_id` PRIMARY KEY(`id`),
	CONSTRAINT `pacientes_id_paciente_unique` UNIQUE(`id_paciente`)
);
--> statement-breakpoint
ALTER TABLE `atendimentos` ADD CONSTRAINT `atendimentos_paciente_id_pacientes_id_fk` FOREIGN KEY (`paciente_id`) REFERENCES `pacientes`(`id`) ON DELETE no action ON UPDATE no action;