DROP TABLE `agendamentos`;--> statement-breakpoint
DROP TABLE `alergias`;--> statement-breakpoint
DROP TABLE `atendimentos`;--> statement-breakpoint
DROP TABLE `audit_log`;--> statement-breakpoint
DROP TABLE `backup_config`;--> statement-breakpoint
DROP TABLE `backup_history`;--> statement-breakpoint
DROP TABLE `bloqueios_horario`;--> statement-breakpoint
DROP TABLE `cardiologia`;--> statement-breakpoint
DROP TABLE `cirurgias`;--> statement-breakpoint
DROP TABLE `cross_tenant_access_logs`;--> statement-breakpoint
DROP TABLE `dashboard_configs`;--> statement-breakpoint
DROP TABLE `documentos_externos`;--> statement-breakpoint
DROP TABLE `documentos_medicos`;--> statement-breakpoint
DROP TABLE `endoscopias`;--> statement-breakpoint
DROP TABLE `evolucoes`;--> statement-breakpoint
DROP TABLE `exames_favoritos`;--> statement-breakpoint
DROP TABLE `exames_imagem`;--> statement-breakpoint
DROP TABLE `exames_laboratoriais`;--> statement-breakpoint
DROP TABLE `exames_padronizados`;--> statement-breakpoint
DROP TABLE `historico_agendamentos`;--> statement-breakpoint
DROP TABLE `historico_medidas`;--> statement-breakpoint
DROP TABLE `historico_solicitacao_cirurgica`;--> statement-breakpoint
DROP TABLE `historico_vinculo`;--> statement-breakpoint
DROP TABLE `internacoes`;--> statement-breakpoint
DROP TABLE `medicamentos_uso`;--> statement-breakpoint
DROP TABLE `obstetricia`;--> statement-breakpoint
DROP TABLE `paciente_autorizacoes`;--> statement-breakpoint
DROP TABLE `pacientes`;--> statement-breakpoint
DROP TABLE `patologias`;--> statement-breakpoint
DROP TABLE `problemas_ativos`;--> statement-breakpoint
DROP TABLE `profissionais`;--> statement-breakpoint
DROP TABLE `resultados_laboratoriais`;--> statement-breakpoint
DROP TABLE `resumo_clinico`;--> statement-breakpoint
DROP TABLE `solicitacoes_cirurgicas`;--> statement-breakpoint
DROP TABLE `tenants`;--> statement-breakpoint
DROP TABLE `terapias`;--> statement-breakpoint
DROP TABLE `user_profiles`;--> statement-breakpoint
DROP TABLE `user_settings`;--> statement-breakpoint
DROP TABLE `vinculo_secretaria_medico`;--> statement-breakpoint
ALTER TABLE `users` DROP FOREIGN KEY `users_tenant_id_tenants_id_fk`;
--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `tenant_id`;