/**
 * Lista de Especialidades Médicas reconhecidas pelo CFM
 * Fonte: Resolução CFM nº 2.330/2023
 * Total: 55 especialidades
 */
export const ESPECIALIDADES_MEDICAS = [
  "Acupuntura",
  "Alergia e Imunologia",
  "Anestesiologia",
  "Angiologia",
  "Cancerologia (Oncologia)",
  "Cardiologia",
  "Cirurgia Cardiovascular",
  "Cirurgia da Mão",
  "Cirurgia de Cabeça e Pescoço",
  "Cirurgia do Aparelho Digestivo",
  "Cirurgia Geral",
  "Cirurgia Oncológica",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Clínica Médica (Medicina Interna)",
  "Coloproctologia",
  "Dermatologia",
  "Endocrinologia e Metabologia",
  "Endoscopia",
  "Gastroenterologia",
  "Genética Médica",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia e Hemoterapia",
  "Homeopatia",
  "Infectologia",
  "Mastologia",
  "Medicina de Emergência",
  "Medicina de Família e Comunidade",
  "Medicina do Trabalho",
  "Medicina do Tráfego",
  "Medicina Esportiva",
  "Medicina Física e Reabilitação",
  "Medicina Intensiva",
  "Medicina Legal e Perícia Médica",
  "Medicina Nuclear",
  "Medicina Preventiva e Social",
  "Nefrologia",
  "Neurocirurgia",
  "Neurologia",
  "Nutrologia",
  "Oftalmologia",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Patologia",
  "Patologia Clínica/Medicina Laboratorial",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Radiologia e Diagnóstico por Imagem",
  "Radioterapia",
  "Reumatologia",
  "Urologia",
] as const;

/**
 * Áreas de Atuação reconhecidas pelo CFM
 * Fonte: Resolução CFM nº 2.330/2023
 */
export const AREAS_ATUACAO = [
  "Administração em Saúde",
  "Alergia e Imunologia Pediátrica",
  "Angiorradiologia e Cirurgia Endovascular",
  "Atendimento ao Queimado",
  "Cardiologia Pediátrica",
  "Cirurgia Crânio-Maxilo-Facial",
  "Cirurgia do Trauma",
  "Cirurgia Videolaparoscópica",
  "Citopatologia",
  "Densitometria Óssea",
  "Dor",
  "Ecocardiografia",
  "Ecografia Vascular com Doppler",
  "Eletrofisiologia Clínica Invasiva",
  "Emergência Pediátrica",
  "Endocrinologia Pediátrica",
  "Endoscopia Digestiva",
  "Endoscopia Ginecológica",
  "Endoscopia Respiratória",
  "Ergometria",
  "Foniatria",
  "Gastroenterologia Pediátrica",
  "Hansenologia",
  "Hematologia e Hemoterapia Pediátrica",
  "Hemodinâmica e Cardiologia Intervencionista",
  "Hepatologia",
  "Infectologia Hospitalar",
  "Infectologia Pediátrica",
  "Mamografia",
  "Medicina Aeroespacial",
  "Medicina do Adolescente",
  "Medicina do Sono",
  "Medicina Fetal",
  "Medicina Intensiva Pediátrica",
  "Medicina Paliativa",
  "Medicina Tropical",
  "Nefrologia Pediátrica",
  "Neonatologia",
  "Neurofisiologia Clínica",
  "Neurologia Pediátrica",
  "Neurorradiologia",
  "Nutrição Parenteral e Enteral",
  "Nutrição Parenteral e Enteral Pediátrica",
  "Nutrologia Pediátrica",
  "Pneumologia Pediátrica",
  "Psicogeriatria",
  "Psicoterapia",
  "Psiquiatria da Infância e Adolescência",
  "Psiquiatria Forense",
  "Radiologia Intervencionista e Angiorradiologia",
  "Reprodução Assistida",
  "Reumatologia Pediátrica",
  "Sexologia",
  "Transplante de Medula Óssea",
  "Ultrassonografia em Ginecologia e Obstetrícia",
] as const;

export type EspecialidadeMedica = typeof ESPECIALIDADES_MEDICAS[number];
export type AreaAtuacao = typeof AREAS_ATUACAO[number];
